New param `showOnlyAvailable` to `chaordicRecommendations` query.
vtex-apps/chaordic-graphql pull request #10
Opened 2020-06-03 21:18 UTC by gustavopvasconcellos

Link to test:
https://dev1004--carrefourbr.myvtex.com/_v/private/vtex.chaordic-graphql@2.1.0/graphiql/v1?operationName=chaordicRecommendations&variables=%7B%0A%20%20%22chaordicBrowserId%22%3A%20%22a20b6961-2f8a-4fdb-80e2-1173de4f4027%22%2C%0A%22pathName%22%3A%20%22%2Fteste-corredor%2Fteste-categoria%22%2C%0A%22salesChannel%22%3A%20%222%22%2C%0A%22source%22%3A%20%22desktop%22%2C%0A%22name%22%3A%20%22home%22%0A%0A%7D

2020-06-03 21:56 UTC, Klynger requested changes
I think it would be better if you use an enum instead of a boolean and then change the param to something like `filter: 'none' | 'onlyAvailable' | 'something-else' | ...`

2020-06-03 22:00 UTC, Klynger commented
> I think it would be better if you use an enum instead of a boolean and then change the param to something like `filter: 'none' | 'onlyAvailable' | 'something-else' | ...`

I used filter only as an example, but I don't know if this is a good name

2020-06-09 13:32 UTC, gustavopvasconcellos commented
> I think it would be better if you use an enum instead of a boolean and then change the param to something like `filter: 'none' | 'onlyAvailable' | 'something-else' | ...`

@Klynger The API only supports the boolean values, so I think the boolean value in this case is better to understand and link the query param with the API docs.

https://docs.linximpulse.com/v3-search/docs/search

2020-06-09 14:22 UTC, Klynger approved these changes

2020-06-22 20:26 UTC, merged