Sales channel
vtex-apps/chaordic-graphql pull request #12
Opened 2020-07-30 21:43 UTC by gustavopvasconcellos

https://shelfregion--carrefourbrfood.myvtex.com/_v/private/vtex.chaordic-graphql@2.3.0/graphiql/v1?operationName=chaordicRecommendations&variables=%7B%0A%22chaordicBrowserId%22%3A%20%22undefined%22%2C%0A%20%20%22pathName%22%3A%20%22%2F%22%2C%0A%20%20%22salesChannel%22%3A%20%221%22%2C%0A%20%20%22source%22%3A%20%22desktop%22%2C%0A%0A%22name%22%3A%20%22home%22%0A%0A%7D'

I've added a nullish conditioner to prioritize when the salesChannel is sent on the search request

2020-07-31 12:48 UTC, klzns requested changes
Missing changelog

2020-07-31 12:48 UTC, klzns commented on node/clients/search.ts
> +    return this.get(this.routes.popular, { metric: 'chaordic-popularq' })
Indented?

2020-07-31 16:51 UTC, klzns commented on node/clients/search.ts
> +    return this.get(this.routes.popular, { metric: 'chaordic-popularq' })
Ops *intentional?

2020-08-03 16:47 UTC, gustavopvasconcellos commented
@klzns I've updated the changelog and the typo, please review it ;)

2020-08-03 18:32 UTC, klzns requested changes

2020-08-03 18:32 UTC, klzns commented on CHANGELOG.md
> +- Priorize `salesChannel` parameter
```suggestion
- Prioritize `salesChannel` parameter 
```

2020-08-03 18:32 UTC, klzns approved these changes

2020-08-03 18:32 UTC, merged